# Generated by Django 5.2.16 on 2026-07-28 00:02

import django.db.models.deletion
import support_requests.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportProviderConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('backend_key', models.CharField(max_length=50)),
                ('base_url', models.URLField(blank=True, default='')),
                ('api_token', models.CharField(blank=True, default='', max_length=255)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'support_requests_provider_config',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SupportDestination',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('remote_project', models.CharField(max_length=255)),
                ('default_labels', models.JSONField(blank=True, default=list)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='support_requests.supportproviderconfig')),
            ],
            options={
                'db_table': 'support_requests_destination',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SupportRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('pending', 'Pending'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=16)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High')], default='normal', max_length=16)),
                ('category', models.CharField(choices=[('bug', 'Bug'), ('feature', 'Feature'), ('account', 'Account'), ('billing', 'Billing'), ('other', 'Other')], default='other', max_length=16)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('last_requester_activity_at', models.DateTimeField(blank=True, null=True)),
                ('last_staff_activity_at', models.DateTimeField(blank=True, null=True)),
                ('last_escalated_at', models.DateTimeField(blank=True, null=True)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'support_requests_request',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author_role', models.CharField(choices=[('user', 'User'), ('support', 'Support'), ('system', 'System')], default='user', max_length=16)),
                ('body', models.TextField()),
                ('is_internal', models.BooleanField(default=False)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_request_messages', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='support_requests.supportrequest')),
            ],
            options={
                'db_table': 'support_requests_message',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportEscalation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('opened', 'Opened'), ('failed', 'Failed')], default='opened', max_length=16)),
                ('remote_issue_id', models.CharField(blank=True, default='', max_length=80)),
                ('remote_issue_number', models.CharField(blank=True, default='', max_length=80)),
                ('remote_issue_url', models.URLField(blank=True, default='', max_length=500)),
                ('title_snapshot', models.CharField(max_length=200)),
                ('body_snapshot', models.TextField()),
                ('forwarded_attachments', models.JSONField(blank=True, default=list)),
                ('provider_response', models.JSONField(blank=True, default=dict)),
                ('failure_message', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_request_escalations', to=settings.AUTH_USER_MODEL)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalations', to='support_requests.supportdestination')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalations', to='support_requests.supportrequest')),
            ],
            options={
                'db_table': 'support_requests_escalation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportRequestAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('attachment', 'Attachment'), ('screenshot', 'Screenshot'), ('log_bundle', 'Log bundle'), ('other', 'Other')], default='attachment', max_length=32)),
                ('file', models.FileField(upload_to=support_requests.models.support_request_attachment_upload_to)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField()),
                ('content_type', models.CharField(blank=True, default='', max_length=120)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='support_requests.supportrequest')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_request_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'support_requests_attachment',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='supportdestination',
            index=models.Index(fields=['provider', 'is_active'], name='support_req_provide_0c5414_idx'),
        ),
        migrations.AddIndex(
            model_name='supportrequest',
            index=models.Index(fields=['requester', 'status'], name='support_req_request_3532ad_idx'),
        ),
        migrations.AddIndex(
            model_name='supportrequest',
            index=models.Index(fields=['status', 'priority'], name='support_req_status_ceefad_idx'),
        ),
        migrations.AddIndex(
            model_name='supportmessage',
            index=models.Index(fields=['request', 'created_at'], name='support_req_request_e66a44_idx'),
        ),
        migrations.AddIndex(
            model_name='supportescalation',
            index=models.Index(fields=['request', 'created_at'], name='support_req_request_defe46_idx'),
        ),
        migrations.AddIndex(
            model_name='supportescalation',
            index=models.Index(fields=['destination', 'created_at'], name='support_req_destina_165735_idx'),
        ),
        migrations.AddIndex(
            model_name='supportrequestattachment',
            index=models.Index(fields=['request', 'created_at'], name='support_req_request_f556ea_idx'),
        ),
    ]
